In [70]:
import numpy as numpy
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [71]:
data = pd.read_csv(
    "C:\\Users\\borde\\OneDrive\\Desktop\\ML_project\\notebook\\data\\system_telemetry_dataset.csv"
)

In [72]:
data

,Machine_ID,Timestamp,CPU_Temp_C,GPU_Temp_C,CPU_Usage_Pct,GPU_Usage_Pct,RAM_Usage_Pct,Disk_Usage_Pct,Disk_IO_MBps,Battery_Level_Pct,Fan_Speed_RPM,System_Event,Failure_Status
0,MACHINE_001,2025-01-01 00:00:00,47.36,68.42,50.26,37.93,37.02,27.02,16.39,93.3,2821,NORMAL_OPERATION,0
1,MACHINE_002,2025-01-01 00:10:00,35.68,69.04,55.78,16.68,38.18,28.25,43.47,76.2,2534,NORMAL_OPERATION,0
2,MACHINE_003,2025-01-01 00:20:00,55.19,42.46,26.07,25.15,50.52,55.33,31.96,75.7,2807,NORMAL_OPERATION,0
3,MACHINE_004,2025-01-01 00:30:00,55.05,43.46,13.58,57.19,73.45,56.38,43.51,54.9,2963,NORMAL_OPERATION,0
4,MACHINE_005,2025-01-01 00:40:00,77.81,88.40,80.69,97.73,86.40,88.55,243.51,25.6,5093,CRITICAL_THERMAL_THROTTLE,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,MACHINE_2996,2025-01-21 19:10:00,37.12,48.29,29.33,49.53,63.10,51.02,12.40,95.5,2166,NORMAL_OPERATION,0
2996,MACHINE_2997,2025-01-21 19:20:00,37.04,40.61,10.53,36.13,58.32,22.27,41.95,92.6,1972,NORMAL_OPERATION,0
2997,MACHINE_2998,2025-01-21 19:30:00,49.00,64.95,24.02,59.84,45.99,37.39,23.43,84.0,2213,NORMAL_OPERATION,0
2998,MACHINE_2999,2025-01-21 19:40:00,42.36,50.41,57.12,45.64,36.96,47.35,79.15,54.5,2591,NORMAL_OPERATION,0
2999,MACHINE_3000,2025-01-21 19:50:00,50.42,62.87,18.70,11.78,42.12,62.85,92.26,51.0,2481,NORMAL_OPERATION,0

In [73]:
data.head()

,Machine_ID,Timestamp,CPU_Temp_C,GPU_Temp_C,CPU_Usage_Pct,GPU_Usage_Pct,RAM_Usage_Pct,Disk_Usage_Pct,Disk_IO_MBps,Battery_Level_Pct,Fan_Speed_RPM,System_Event,Failure_Status
0,MACHINE_001,2025-01-01 00:00:00,47.36,68.42,50.26,37.93,37.02,27.02,16.39,93.3,2821,NORMAL_OPERATION,0
1,MACHINE_002,2025-01-01 00:10:00,35.68,69.04,55.78,16.68,38.18,28.25,43.47,76.2,2534,NORMAL_OPERATION,0
2,MACHINE_003,2025-01-01 00:20:00,55.19,42.46,26.07,25.15,50.52,55.33,31.96,75.7,2807,NORMAL_OPERATION,0
3,MACHINE_004,2025-01-01 00:30:00,55.05,43.46,13.58,57.19,73.45,56.38,43.51,54.9,2963,NORMAL_OPERATION,0
4,MACHINE_005,2025-01-01 00:40:00,77.81,88.40,80.69,97.73,86.40,88.55,243.51,25.6,5093,CRITICAL_THERMAL_THROTTLE,1

In [74]:
data.nunique()

Machine_ID           3000
Timestamp            3000
CPU_Temp_C           2156
GPU_Temp_C           2125
CPU_Usage_Pct        2427
GPU_Usage_Pct        2409
RAM_Usage_Pct        2306
Disk_Usage_Pct       2330
Disk_IO_MBps         2685
Battery_Level_Pct     692
Fan_Speed_RPM        1626
System_Event            7
Failure_Status          2
dtype: int64

In [75]:
data.drop(["Machine_ID"], axis=1, inplace=True, errors="ignore")

In [76]:


# data.to_csv("data\machine_failure_data.csv", index=False)

In [77]:
#  Display first few rows
print("First 5 rows:")
print(data.head())

print("\nDataset shape:", data.shape)
print("\nColumn names:")
print(data.columns.tolist())

First 5 rows:
             Timestamp  CPU_Temp_C  GPU_Temp_C  CPU_Usage_Pct  GPU_Usage_Pct  \
0  2025-01-01 00:00:00       47.36       68.42          50.26          37.93
1  2025-01-01 00:10:00       35.68       69.04          55.78          16.68
2  2025-01-01 00:20:00       55.19       42.46          26.07          25.15
3  2025-01-01 00:30:00       55.05       43.46          13.58          57.19
4  2025-01-01 00:40:00       77.81       88.40          80.69          97.73

   RAM_Usage_Pct  Disk_Usage_Pct  Disk_IO_MBps  Battery_Level_Pct  \
0          37.02           27.02         16.39               93.3
1          38.18           28.25         43.47               76.2
2          50.52           55.33         31.96               75.7
3          73.45           56.38         43.51               54.9
4          86.40           88.55        243.51               25.6

   Fan_Speed_RPM               System_Event  Failure_Status
0           2821           NORMAL_OPERATION               0
1           2534           NORMAL_OPERATION               0
2           2807           NORMAL_OPERATION               0
3           2963           NORMAL_OPERATION               0
4           5093  CRITICAL_THERMAL_THROTTLE               1

Dataset shape: (3000, 12)

Column names:
['Timestamp', 'CPU_Temp_C', 'GPU_Temp_C', 'CPU_Usage_Pct', 'GPU_Usage_Pct', 'RAM_Usage_Pct', 'Disk_Usage_Pct', 'Disk_IO_MBps', 'Battery_Level_Pct', 'Fan_Speed_RPM', 'System_Event', 'Failure_Status']

In [78]:
print("\nDataset information:")
print(data.info())

print("\nStatistical summary:")
print(data.describe())

print("\nMissing values:")
print(data.isnull().sum())

print("\nDuplicate rows:", data.duplicated().sum())

Dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Timestamp          3000 non-null   str
 1   CPU_Temp_C         3000 non-null   float64
 2   GPU_Temp_C         3000 non-null   float64
 3   CPU_Usage_Pct      3000 non-null   float64
 4   GPU_Usage_Pct      3000 non-null   float64
 5   RAM_Usage_Pct      3000 non-null   float64
 6   Disk_Usage_Pct     3000 non-null   float64
 7   Disk_IO_MBps       3000 non-null   float64
 8   Battery_Level_Pct  3000 non-null   float64
 9   Fan_Speed_RPM      3000 non-null   int64
 10  System_Event       3000 non-null   str
 11  Failure_Status     3000 non-null   int64
dtypes: float64(8), int64(2), str(2)
memory usage: 281.4 KB
None

Statistical summary:
        CPU_Temp_C   GPU_Temp_C  CPU_Usage_Pct  GPU_Usage_Pct  RAM_Usage_Pct  \
count  3000.000000  3000.000000    3000.000000    3000.000000    3000.000000
mean     54.873833    57.178720      42.906960      38.363097      56.283747
std      13.907291    13.898269      21.719926      22.206179      16.651248
min      35.000000    38.000000      10.000000       5.010000      30.010000
25%      44.330000    46.200000      25.320000      21.592500      42.855000
50%      53.170000    55.340000      40.975000      36.120000      54.600000
75%      62.292500    64.430000      56.195000      50.642500      67.160000
max      97.910000    98.970000      99.980000      99.910000      98.750000

       Disk_Usage_Pct  Disk_IO_MBps  Battery_Level_Pct  Fan_Speed_RPM  \
count     3000.000000   3000.000000        3000.000000    3000.000000
mean        46.645937     87.514243          70.036633    2891.499667
std         17.656696     79.326771          20.525212     845.685188
min         20.010000     10.050000          10.000000    1800.000000
25%         32.525000     40.957500          58.400000    2301.750000
50%         44.975000     71.000000          72.000000    2762.500000
75%         57.660000    100.135000          86.200000    3223.500000
max         97.900000    448.800000         100.000000    5953.000000

       Failure_Status
count     3000.000000
mean         0.099333
std          0.299159
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000

Missing values:
Timestamp            0
CPU_Temp_C           0
GPU_Temp_C           0
CPU_Usage_Pct        0
GPU_Usage_Pct        0
RAM_Usage_Pct        0
Disk_Usage_Pct       0
Disk_IO_MBps         0
Battery_Level_Pct    0
Fan_Speed_RPM        0
System_Event         0
Failure_Status       0
dtype: int64

Duplicate rows: 0

In [79]:
# data.drop(columns=["Machine_ID"], inplace=True)

In [80]:

# 3. REMOVE DUPLICATE ROWS

data = data.drop_duplicates()

print("\nShape after removing duplicates:", data.shape)

Shape after removing duplicates: (3000, 12)

In [81]:
import pandas as pd
# 4. CONVERT TIMESTAMP TO DATETIME
data["Timestamp"] = pd.to_datetime(data["Timestamp"], errors="coerce")

# Check invalid timestamps
print("\nInvalid timestamps:",
      data["Timestamp"].isnull().sum())

Invalid timestamps: 0

In [82]:






# 7. CHECK DATA TYPES


numeric_columns = [
    "Timestamp",
    "CPU_Temp_C",
    "GPU_Temp_C",
    "CPU_Usage_Pct",
    "GPU_Usage_Pct",
    "RAM_Usage_Pct",
    "Disk_Usage_Pct",
    "Disk_IO_MBps",
    "Battery_Level_Pct",
    "Fan_Speed_RPM",
    
]

target_column = "Failure_Status"

# Convert numeric columns to numeric values
for col in numeric_columns + [target_column]:
    data[col] = pd.to_numeric(data[col], errors="coerce")

In [83]:
from sklearn.impute import SimpleImputer

# 8. HANDLE MISSING VALUES
# Median imputation for numerical features
imputer = SimpleImputer(strategy="median")

data[numeric_columns] = imputer.fit_transform(
    data[numeric_columns]
)

# Remove rows where target is missing
df = data.dropna(subset=[target_column])

In [84]:
df = pd.get_dummies(df, columns=["System_Event"], dtype=int)

In [85]:
df.to_csv("system_telemetry_dataset.csv", index=False)